version: '2'

volumes:
  orderer.ordermanagement.com:
  peer0.Audi.ordermanagement.com:
  peer1.Audi.ordermanagement.com:
  peer0.MRF.ordermanagement.com:
  peer1.MRF.ordermanagement.com:
  peer0.BridgeStone.ordermanagement.com:
  peer1.BridgeStone.ordermanagement.com:

networks:
  ordermanagement:

services:

  orderer.ordermanagement.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ordermanagement.com
    container_name: orderer.ordermanagement.com
    networks:
      - ordermanagement

  peer0.Audi.ordermanagement.com:
    container_name: peer0.Audi.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Audi.ordermanagement.com
    networks:
      - ordermanagement

  peer1.Audi.ordermanagement.com:
    container_name: peer1.Audi.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Audi.ordermanagement.com
    networks:
      - ordermanagement

  peer0.MRF.ordermanagement.com:
    container_name: peer0.MRF.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.MRF.ordermanagement.com
    networks:
      - ordermanagement

  peer1.MRF.ordermanagement.com:
    container_name: peer1.MRF.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.MRF.ordermanagement.com
    networks:
      - ordermanagement

  peer0.BridgeStone.ordermanagement.com:
    container_name: peer0.BridgeStone.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.BridgeStone.ordermanagement.com
    networks:
      - ordermanagement

  peer1.BridgeStone.ordermanagement.com:
    container_name: peer1.BridgeStone.ordermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.BridgeStone.ordermanagement.com
    networks:
      - ordermanagement

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Audi.ordermanagement.com:7051
      - CORE_PEER_LOCALMSPID=AudiMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Audi.ordermanagement.com/peers/peer0.Audi.ordermanagement.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Audi.ordermanagement.com/peers/peer0.Audi.ordermanagement.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Audi.ordermanagement.com/peers/peer0.Audi.ordermanagement.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Audi.ordermanagement.com/users/Admin@Audi.ordermanagement.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ordermanagement.com
      - peer0.Audi.ordermanagement.com
      - peer1.Audi.ordermanagement.com
      - peer0.MRF.ordermanagement.com
      - peer1.MRF.ordermanagement.com
      - peer0.BridgeStone.ordermanagement.com
      - peer1.BridgeStone.ordermanagement.com
    networks:
      - ordermanagement